### ISSUE TITLE
MutationObserver issue

### ISSUE THREAD

**Issue by ArjixWasTaken** [Only1337/AutoCompleteOFF#2]
Small issue that slipped by since I did not test the code, the current implementation doesn't iterate over the child nodes, it does nothing to be exact.

**Comment by ArjixWasTaken** [comment]
Will post a fix in a moment.

**Comment by illegalsolutions** [comment]
> Will post a fix in a moment.

Thank you for your contribution <3

**Comment by ArjixWasTaken** [comment]
That's what happens when I am overconfident and don't even test the code beforehand 😅
